name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install prerequirements
      run: |
        sudo apt-get install -y python-pip
    - name: Run test
      run: |
        pip install cwltool
        cwltool splitlines.cwl --file inputfile.txt
